version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - TRINO_HOST=trino
      - TRINO_PORT=8080
    depends_on:
      - neo4j
    networks:
      - familytree

  neo4j:
    image: neo4j:5.13
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_max__size=4G
    volumes:
      - neo4j_data:/data
    networks:
      - familytree

networks:
  familytree:
    driver: bridge

volumes:
  neo4j_data:
