# """
# Residents Link Builder - Creates sponsorship relationships
# CSV-based version - FIXED column name issue
# """
# from pyspark.sql import SparkSession
# from pyspark.sql import functions as F

# # ── CONFIG: edit these paths only ──────────────────────────────────────────────
# RPE_PATH   = "./new_data_sc_map/output/residents_person_entity/*.csv"         # e.g. "./person_master.csv" or "./person_master/*.csv"
# RPA_PATH   = "./new_data_sc_map/output/residents_person_alias/*.csv"
# CPA_PATH   = "./new_data_sc_map/output/citizens_person_entity/*.csv"

# OUTPUT_DIR   = "./new_data_sc_map/output/links"                       # local folder for outputs
# DELIMITER    = ","                           # CSV delimiter
# HAS_HEADER   = True                          # set False if no header in source CSV
# INFER_SCHEMA = True                          # set False to read all columns as strings
# SINGLE_FILE  = True                          # True = one CSV per table (coalesce to 1)
# # ──────────────────────────────────────────────────────────────────────────────

# # helper to normalize sponsor numbers to a pure string key
# def normalize_digits(col):
#     # cast to string, remove non-digits, then strip leading zeros
#     return F.regexp_replace(
#         F.regexp_replace(F.col(col).cast("string"), r"[^0-9]", ""), r"^0+", ""
#     )


# def main():
#     spark = SparkSession.builder \
#         .appName("residents_link_builder") \
#         .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
#         .getOrCreate()
    
#     print("RESIDENTS LINK BUILDER - CSV VERSION")
    
#     # Read from CSV files (all from /jobs/output/ - outputs from previous steps)
#     print("Reading input CSV files...")
    
#     # residents_entity = spark.read.csv(
#     #     "/jobs/output/residents_person_entity/*.csv",
#     #     header=True,
#     #     inferSchema=True
#     # )

#     residents_entity = spark.read \
#         .option("header", str(HAS_HEADER).lower()) \
#         .option("inferSchema", str(INFER_SCHEMA).lower()) \
#         .option("sep", DELIMITER) \
#         .option("mode", "PERMISSIVE") \
#         .option("multiLine", "true") \
#         .option("quote", '"') \
#         .option("escape", '"') \
#         .csv(RPE_PATH)
    
#     # residents_alias = spark.read.csv(
#     #     "/jobs/output/residents_person_alias/*.csv",
#     #     header=True,
#     #     inferSchema=True
#     # )

#     residents_alias = spark.read \
#         .option("header", str(HAS_HEADER).lower()) \
#         .option("inferSchema", str(INFER_SCHEMA).lower()) \
#         .option("sep", DELIMITER) \
#         .option("mode", "PERMISSIVE") \
#         .option("multiLine", "true") \
#         .option("quote", '"') \
#         .option("escape", '"') \
#         .csv(RPA_PATH)
    
#     # # Read citizens alias from output (generated by citizens deduplication)
#     # citizens_alias = spark.read.csv(
#     #     "/jobs/output/citizens_person_alias/*.csv",
#     #     header=True,
#     #     inferSchema=True
#     # )

#     # Read citizens alias from output (generated by citizens deduplication)
#     citizens_alias = spark.read \
#         .option("header", str(HAS_HEADER).lower()) \
#         .option("inferSchema", str(INFER_SCHEMA).lower()) \
#         .option("sep", DELIMITER) \
#         .option("mode", "PERMISSIVE") \
#         .option("multiLine", "true") \
#         .option("quote", '"') \
#         .option("escape", '"') \
#         .csv(CPA_PATH)
    
#     print("✓ All CSV files loaded")
#     print(f"  - Residents entities: {residents_entity.count()}")
#     print(f"  - Residents aliases: {residents_alias.count()}")
#     print(f"  - Citizens aliases: {citizens_alias.count()}")
    
#     # Get sponsors from both citizens and residents
#     # FIXED: Rename THEN select the renamed column
#     all_sponsors = citizens_alias \
#         .withColumnRenamed("primary_spm_person_no", "sponsor_spm") \
#         .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
#         .withColumn("sponsor_type", F.lit("citizen")) \
#         .withColumn("sponsor_spm", normalize_digits("sponsor_spm")) \
#         .select("sponsor_spm", "sponsor_entity_id", "sponsor_type") \
#         .union(
#             residents_alias \
#             .withColumnRenamed("SPM_PERSON_NO", "sponsor_spm") \
#             .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
#             .withColumn("sponsor_type", F.lit("resident")) \
#             .withColumn("sponsor_spm", normalize_digits("sponsor_spm")) \
#             .select("sponsor_spm", "sponsor_entity_id", "sponsor_type")
#         )
    
#     print(f"✓ Total sponsors available: {all_sponsors.count()}")
    
#     # Create sponsorship links
#     sponsorship_links = residents_entity.join(
#         all_sponsors,
#         residents_entity.sponsor_number == all_sponsors.sponsor_spm,
#         "left"
#     ).filter(
#         "sponsor_entity_id IS NOT NULL AND entity_person_id IS NOT NULL"
#     ).select(
#         F.col("sponsor_entity_id").alias("sponsor_entity_person_id"),
#         F.col("entity_person_id").alias("sponsored_entity_person_id"),
#         F.col("relation_to_sponsor"),
#         F.col("relationship_code"),
#         F.col("sponsor_type"),
#         F.lit("echannels_residency").alias("source"),
#         F.lit(1.0).alias("confidence")
#     ).dropDuplicates()
    
#     # Create family groups
#     family_groups = residents_entity.join(
#         all_sponsors,
#         residents_entity.sponsor_number == all_sponsors.sponsor_spm,
#         "left"
#     ).filter("sponsor_entity_id IS NOT NULL").select(
#         F.col("entity_person_id"),
#         F.col("sponsor_entity_id").alias("sponsor_id"),
#         F.col("sponsor_number"),
#         F.concat(F.lit("SPON:"), F.col("sponsor_number")).alias("family_group_id"),
#         F.lit("sponsorship").alias("source")
#     ).dropDuplicates()

#         # ---- Write outputs as local CSVs ------------------------------------------
#     out_spon = f"{OUTPUT_DIR.rstrip('/')}/residents_sponsorship_links"
#     out_fam = f"{OUTPUT_DIR.rstrip('/')}/residents_family_groups"
    
#     # Write to CSV files
#     print(f"\n✓ Writing {sponsorship_links.count()} sponsorship links")
#     sponsorship_links.coalesce(1).write \
#         .mode("overwrite") \
#         .option("header", "true") \
#         .csv(out_spon)
    
#     print(f"✓ Writing {family_groups.count()} family groups")
#     family_groups.coalesce(1).write \
#         .mode("overwrite") \
#         .option("header", "true") \
#         .csv(out_fam)
    
#     print("\n✓ RESIDENTS LINK BUILDER COMPLETE")
#     print("Output files saved in:")
#     print("  - /jobs/output/residents_sponsorship_links/")
#     print("  - /jobs/output/residents_family_groups/")
    
#     spark.stop()


# if __name__ == "__main__":
#     main()


"""
Residents Family Links Builder
Creates parent-child and spousal relationships for Neo4j
Extracts family links based on relationship codes
"""
from pyspark.sql import SparkSession
from pyspark.sql import functions as F


# ── CONFIG ─────────────────────────────────────────────────────────────────────
RPE_PATH   = "./new_data_sc_map/output/residents_v2/residents_person_entity/*.csv"
RPA_PATH   = "./new_data_sc_map/output/residents_v2/residents_person_alias/*.csv"
CPE_PATH   = "./new_data_sc_map/output/citizens_v5/citizens_person_entity/*.csv"
CPA_PATH   = "./new_data_sc_map/output/citizens_v5/citizens_person_alias/*.csv"
OUTPUT_DIR = "./new_data_sc_map/output/residents_v2"
DELIMITER  = ","
HAS_HEADER = True
INFER_SCHEMA = True
# ───────────────────────────────────────────────────────────────────────────────

def main():
    spark = SparkSession.builder \
        .appName("residents_family_links_builder") \
        .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
        .getOrCreate()
    
    print("=" * 80)
    print("RESIDENTS FAMILY LINKS BUILDER")
    print("=" * 80)
    
    # Read input CSV files
    print("Reading input CSV files...")
    
    residents_entity = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(RPE_PATH)
    
    residents_alias = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(RPA_PATH)
    
    citizens_entity = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(CPE_PATH)
    
    citizens_alias = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(CPA_PATH)
    
    print("✓ All CSV files loaded")
    print(f"  - Residents entities: {residents_entity.count()}")
    print(f"  - Residents aliases: {residents_alias.count()}")
    print(f"  - Citizens entities: {citizens_entity.count()}")
    print(f"  - Citizens aliases: {citizens_alias.count()}")
    
    # Create unified sponsor lookup (citizens + residents)
    # FIX: Use correct column name 'spm_person_no' not 'primary_spm_person_no'
    all_sponsors = citizens_alias \
        .withColumnRenamed("spm_person_no", "sponsor_spm") \
        .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
        .withColumn("sponsor_type", F.lit("citizen")) \
        .select("sponsor_spm", "sponsor_entity_id", "sponsor_type") \
        .union(
            residents_alias \
            .withColumnRenamed("SPM_PERSON_NO", "sponsor_spm") \
            .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
            .withColumn("sponsor_type", F.lit("resident")) \
            .select("sponsor_spm", "sponsor_entity_id", "sponsor_type")
        )
    
    print(f"\n✓ Total sponsors available: {all_sponsors.count()}")
    
    # Show sample sponsors for validation
    print("\nSample sponsors:")
    all_sponsors.show(5, truncate=False)
    
    # Join residents with their full sponsor details
    # FIX: Use sponsor_spm_person_no (from resi_trans) not sponsor_number
    # This correctly links:
    #   - Citizen sponsors (e.g., P0000001001) → their foreign spouse/family
    #   - Resident sponsors (e.g., R0000010005) → their spouse/children
    residents_with_sponsors = residents_entity.alias("r") \
        .join(
            all_sponsors.alias("s"),
            F.col("r.sponsor_spm_person_no") == F.col("s.sponsor_spm"),
            "left"
        )
    
    print(f"\n✓ Matched {residents_with_sponsors.filter(F.col('sponsor_entity_id').isNotNull()).count()} residents with sponsors")
    
    # ====================================================================
    # 1. PARENT-CHILD RELATIONSHIPS
    # ====================================================================
    # Children are those with relationship_code = 3 (son) or 4 (daughter)
    
    parent_child_links = residents_with_sponsors \
        .filter(F.col("relationship_code").isin([3, 4])) \
        .filter(F.col("sponsor_entity_id").isNotNull()) \
        .select(
            # Parent information
            F.col("sponsor_entity_id").alias("parent_entity_id"),
            F.col("sponsor_spm").alias("parent_spm_person_no"),
            F.col("sponsor_type").alias("parent_type"),
            
            # Child information
            F.col("entity_person_id").alias("child_entity_id"),
            F.col("primary_spm_person_no").alias("child_spm_person_no"),
            F.col("full_name").alias("child_full_name"),
            F.col("dob").alias("child_dob"),
            F.col("passport").alias("child_passport"),
            F.col("nationality_code").cast("string").alias("child_nationality"),  # FIX: Cast to string
            F.col("sex").alias("child_sex"),
            
            # Relationship details
            F.when(F.col("relationship_code") == 3, "SON")
             .when(F.col("relationship_code") == 4, "DAUGHTER")
             .otherwise("CHILD").alias("relationship_type"),
            F.col("relation_to_sponsor").alias("relationship_label"),
            F.col("sponsor_number"),
            F.lit("resident_family").alias("source"),
            F.lit(1.0).alias("confidence")
        ).dropDuplicates()
    
    # Enrich with parent full details
    # FIX: Don't use alias prefix in join condition after select
    parent_child_links_enriched = parent_child_links.alias("pc") \
        .join(
            citizens_entity.alias("ce").select(
                F.col("entity_person_id").alias("parent_entity_id"),
                F.col("full_name").alias("parent_full_name"),
                F.col("dob").alias("parent_dob"),
                F.col("national_id").alias("parent_national_id"),
                F.col("nationality_code").cast("string").alias("parent_nationality"),  # FIX: Cast to string
                F.col("sex").alias("parent_sex")
            ),
            on="parent_entity_id",
            how="left"
        ) \
        .join(
            residents_entity.alias("re").select(
                F.col("entity_person_id").alias("parent_entity_id_r"),
                F.col("full_name").alias("parent_full_name_r"),
                F.col("dob").alias("parent_dob_r"),
                F.col("passport").alias("parent_passport_r"),
                F.col("nationality_code").cast("string").alias("parent_nationality_r"),  # FIX: Cast to string
                F.col("sex").alias("parent_sex_r")
            ),
            F.col("parent_entity_id") == F.col("parent_entity_id_r"),  # FIX: No alias prefix
            how="left"
        ) \
        .select(
            F.col("parent_entity_id"),
            F.col("parent_spm_person_no"),
            F.coalesce(F.col("parent_full_name"), F.col("parent_full_name_r")).alias("parent_full_name"),
            F.coalesce(F.col("parent_dob"), F.col("parent_dob_r")).alias("parent_dob"),
            F.coalesce(F.col("parent_national_id"), F.col("parent_passport_r")).alias("parent_id"),
            F.coalesce(F.col("parent_nationality"), F.col("parent_nationality_r")).alias("parent_nationality"),  # Already cast
            F.coalesce(F.col("parent_sex"), F.col("parent_sex_r")).alias("parent_sex"),
            F.col("parent_type"),
            F.col("child_entity_id"),
            F.col("child_spm_person_no"),
            F.col("child_full_name"),
            F.col("child_dob"),
            F.col("child_passport"),
            F.col("child_nationality"),  # Already cast
            F.col("child_sex"),
            F.col("relationship_type"),
            F.col("relationship_label"),
            F.col("sponsor_number"),
            F.col("source"),
            F.col("confidence")
        )
    
    # ====================================================================
    # 2. SPOUSAL RELATIONSHIPS
    # ====================================================================
    # Spouses are those with relationship_code = 2 (wife)
    
    print("\n" + "=" * 80)
    print("2. SPOUSAL RELATIONSHIPS (CORRECTED)")
    print("=" * 80)

    # Step 1: Identify foreign spouses already in citizens family books
    # These should NOT be processed again in residents link builder
    foreign_spouses_in_citizens = citizens_entity.filter(
        F.col("is_emirati") == "N"  # Foreign nationals
    ).select(
        F.col("spm_person_no").alias("citizen_foreign_spouse_spm")
    ).dropDuplicates()

    print(f"✓ Found {foreign_spouses_in_citizens.count()} foreign spouses in citizens family books")
    print("  These will be EXCLUDED from residents spouse link creation")

    # Step 2: Get all residents with relationship_code = 2 (wives)
    residents_spouses = residents_with_sponsors.filter(
        F.col("relationship_code") == 2
    )

    print(f"✓ Found {residents_spouses.count()} resident records with relationship_code=2 (wives)")

    # Step 3: EXCLUDE foreign spouses already in citizens data
    # This prevents creating duplicate spouse links for people like Emma
    residents_spouses_filtered = residents_spouses.join(
        foreign_spouses_in_citizens,
        residents_spouses["primary_spm_person_no"] == foreign_spouses_in_citizens["citizen_foreign_spouse_spm"],
        "left_anti"  # Anti-join: keep only rows that DON'T match
    )

    excluded_count = residents_spouses.count() - residents_spouses_filtered.count()
    print(f"✓ Excluded {excluded_count} foreign spouses already in citizens family books")
    print(f"✓ Remaining {residents_spouses_filtered.count()} residents to process")

    # Step 4: Create spouse links ONLY for the filtered set
    spousal_links = residents_spouses_filtered \
        .filter(F.col("sponsor_entity_id").isNotNull()) \
        .select(
            # Husband information (sponsor)
            F.col("sponsor_entity_id").alias("husband_entity_id"),
            F.col("sponsor_spm").alias("husband_spm_person_no"),
            F.col("sponsor_type").alias("husband_type"),
            
            # Wife information (sponsored)
            F.col("entity_person_id").alias("wife_entity_id"),
            F.col("primary_spm_person_no").alias("wife_spm_person_no"),
            F.col("full_name").alias("wife_full_name"),
            F.col("dob").alias("wife_dob"),
            F.col("passport").alias("wife_passport"),
            F.col("nationality_code").cast("string").alias("wife_nationality"),
            
            # Relationship details
            F.lit("SPOUSE").alias("relationship_type"),
            F.col("relation_to_sponsor").alias("relationship_label"),
            F.col("sponsor_number"),
            F.lit("resident_family").alias("source"),
            F.lit(1.0).alias("confidence")
        ).dropDuplicates()

    # Step 5: Validation - Check for known problematic cases
    print("\n" + "=" * 80)
    print("VALIDATION CHECKS")
    print("=" * 80)

    # Check 1: Ahmed should have NO spouse links here (his wife is Emirati)
    ahmed_check = spousal_links.filter(F.col("husband_spm_person_no") == "P0000001001")
    ahmed_count = ahmed_check.count()

    if ahmed_count > 0:
        print(f"\n🚨 WARNING: Ahmed (P0000001001) has {ahmed_count} spouse link(s) in residents!")
        print("   Ahmed's wife (Mariam) is Emirati and should NOT be in residents.")
        ahmed_check.show(truncate=False)
    else:
        print("\n✓ Ahmed (P0000001001) has NO spouse links in residents (correct)")

    # Check 2: Emma should NOT be in this output
    emma_check = spousal_links.filter(F.col("wife_spm_person_no") == "P0000001026")
    emma_count = emma_check.count()

    if emma_count > 0:
        print(f"\n🚨 WARNING: Emma (P0000001026) has {emma_count} spouse link(s) in residents!")
        print("   Emma is a foreign spouse in Majid's family book and should be EXCLUDED.")
        emma_check.show(truncate=False)
    else:
        print("\n✓ Emma (P0000001026) is NOT in residents spouse links (correct - filtered out)")

    # Check 3: Majid should have NO spouse links here (Emma is in citizens family book)
    majid_check = spousal_links.filter(F.col("husband_spm_person_no") == "P0000001025")
    majid_count = majid_check.count()

    if majid_count > 0:
        print(f"\n🚨 WARNING: Majid (P0000001025) has {majid_count} spouse link(s) in residents!")
        print("   Majid's wife (Emma) is in citizens family book and should be handled there.")
        majid_check.show(truncate=False)
    else:
        print("\n✓ Majid (P0000001025) has NO spouse links in residents (correct)")

    # Step 6: Enrich with husband full details
    spousal_links_enriched = spousal_links.alias("sp") \
        .join(
            citizens_entity.alias("ce").select(
                F.col("entity_person_id").alias("husband_entity_id_c"),
                F.col("full_name").alias("husband_full_name_c"),
                F.col("dob").alias("husband_dob_c"),
                F.col("national_id").alias("husband_national_id_c"),
                F.col("nationality_code").cast("string").alias("husband_nationality_c"),
                F.col("sex").alias("husband_sex_c")
            ),
            F.col("sp.husband_entity_id") == F.col("ce.husband_entity_id_c"),
            "left"
        ) \
        .join(
            residents_entity.alias("re").select(
                F.col("entity_person_id").alias("husband_entity_id_r"),
                F.col("full_name").alias("husband_full_name_r"),
                F.col("dob").alias("husband_dob_r"),
                F.col("passport").alias("husband_passport_r"),
                F.col("nationality_code").cast("string").alias("husband_nationality_r"),
                F.col("sex").alias("husband_sex_r")
            ),
            F.col("sp.husband_entity_id") == F.col("re.husband_entity_id_r"),
            "left"
        ) \
        .select(
            F.col("husband_entity_id"),
            F.col("husband_spm_person_no"),
            F.coalesce(F.col("husband_full_name_c"), F.col("husband_full_name_r")).alias("husband_full_name"),
            F.coalesce(F.col("husband_dob_c"), F.col("husband_dob_r")).alias("husband_dob"),
            F.coalesce(F.col("husband_national_id_c"), F.col("husband_passport_r")).alias("husband_id"),
            F.coalesce(F.col("husband_nationality_c"), F.col("husband_nationality_r")).alias("husband_nationality"),
            F.coalesce(F.col("husband_sex_c"), F.col("husband_sex_r")).alias("husband_sex"),
            F.col("husband_type"),
            F.col("wife_entity_id"),
            F.col("wife_spm_person_no"),
            F.col("wife_full_name"),
            F.col("wife_dob"),
            F.col("wife_passport"),
            F.col("wife_nationality"),
            F.col("relationship_type"),
            F.col("relationship_label"),
            F.col("sponsor_number"),
            F.col("source"),
            F.col("confidence")
        )

    print(f"\n✓ Created {spousal_links_enriched.count()} enriched spousal links")

    # ════════════════════════════════════════════════════════════════════════════
    # Additional logging for debugging
    # ════════════════════════════════════════════════════════════════════════════

    print("\n" + "=" * 80)
    print("SPOUSAL LINKS BREAKDOWN")
    print("=" * 80)

    # By husband type
    husband_type_breakdown = spousal_links.groupBy("husband_type").count()
    print("\nBy husband type:")
    husband_type_breakdown.show()

    # By wife nationality
    wife_nationality_breakdown = spousal_links.groupBy("wife_nationality").count()
    print("\nTop 10 wife nationalities:")
    wife_nationality_breakdown.orderBy(F.desc("count")).show(10)

    # Sample records
    print("\nSample spousal links:")
    spousal_links.select(
        "husband_spm_person_no",
        "wife_spm_person_no",
        "relationship_type",
        "husband_type"
    ).show(5, truncate=False)

    print("\n" + "=" * 80)
    print("✓ SPOUSAL RELATIONSHIPS PROCESSING COMPLETE")
    print("=" * 80)
    
    # ====================================================================
    # 3. SPONSORSHIP RELATIONSHIPS (all types)
    # ====================================================================
    sponsorship_links = residents_with_sponsors \
        .filter(F.col("sponsor_entity_id").isNotNull()) \
        .select(
            F.col("sponsor_entity_id").alias("sponsor_entity_person_id"),
            F.col("entity_person_id").alias("sponsored_entity_person_id"),
            F.col("relation_to_sponsor"),
            F.col("relationship_code"),
            F.col("sponsor_type"),
            F.lit("echannels_residency").alias("source"),
            F.lit(1.0).alias("confidence")
        ).dropDuplicates()
    
    # Write outputs
    out_parent_child = f"{OUTPUT_DIR.rstrip('/')}/residents_parent_child_links"
    out_spousal = f"{OUTPUT_DIR.rstrip('/')}/residents_spousal_links"
    out_sponsorship = f"{OUTPUT_DIR.rstrip('/')}/residents_sponsorship_links"
    
    print(f"\n✓ Writing {parent_child_links_enriched.count()} parent-child links")
    parent_child_links_enriched.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .csv(out_parent_child)
    
    print(f"✓ Writing {spousal_links_enriched.count()} spousal links")
    spousal_links_enriched.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .csv(out_spousal)
    
    print(f"✓ Writing {sponsorship_links.count()} sponsorship links")
    sponsorship_links.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .csv(out_sponsorship)
    
    print("\n" + "=" * 80)
    print("✓ RESIDENTS FAMILY LINKS BUILDER COMPLETE")
    print("=" * 80)
    print("Output files saved in:")
    print("  - residents_parent_child_links/ (with full attributes)")
    print("  - residents_spousal_links/ (with full attributes)")
    print("  - residents_sponsorship_links/ (all sponsorship types)")
    print("=" * 80)
    
    # Print summary statistics
    print("\nSummary Statistics:")
    print(f"  Parent-Child relationships: {parent_child_links_enriched.count()}")
    print(f"  Spousal relationships: {spousal_links_enriched.count()}")
    print(f"  Total sponsorship links: {sponsorship_links.count()}")
    
    # Show sample parent-child links
    print("\nSample Parent-Child Links:")
    parent_child_links_enriched.select(
        "parent_full_name", "parent_id", "child_full_name", 
        "child_passport", "relationship_type"
    ).show(5, truncate=False)
    
    # Show sample spousal links
    print("\nSample Spousal Links:")
    spousal_links_enriched.select(
        "husband_full_name", "husband_id", "wife_full_name", 
        "wife_passport", "relationship_type"
    ).show(5, truncate=False)
    
    spark.stop()


if __name__ == "__main__":
    main()