"""
Residents Link Builder - Creates sponsorship relationships
CSV-based version - FIXED column name issue
"""
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

# ── CONFIG: edit these paths only ──────────────────────────────────────────────
RPE_PATH   = "./new_data_sc_map/output/residents_person_entity/*.csv"         # e.g. "./person_master.csv" or "./person_master/*.csv"
RPA_PATH   = "./new_data_sc_map/output/residents_person_alias/*.csv"
CPA_PATH   = "./new_data_sc_map/output/citizens_person_entity/*.csv"

OUTPUT_DIR   = "./new_data_sc_map/output/links"                       # local folder for outputs
DELIMITER    = ","                           # CSV delimiter
HAS_HEADER   = True                          # set False if no header in source CSV
INFER_SCHEMA = True                          # set False to read all columns as strings
SINGLE_FILE  = True                          # True = one CSV per table (coalesce to 1)
# ──────────────────────────────────────────────────────────────────────────────

# helper to normalize sponsor numbers to a pure string key
def normalize_digits(col):
    # cast to string, remove non-digits, then strip leading zeros
    return F.regexp_replace(
        F.regexp_replace(F.col(col).cast("string"), r"[^0-9]", ""), r"^0+", ""
    )


def main():
    spark = SparkSession.builder \
        .appName("residents_link_builder") \
        .config("spark.sql.legacy.timeParserPolicy", "LEGACY") \
        .getOrCreate()
    
    print("RESIDENTS LINK BUILDER - CSV VERSION")
    
    # Read from CSV files (all from /jobs/output/ - outputs from previous steps)
    print("Reading input CSV files...")
    
    # residents_entity = spark.read.csv(
    #     "/jobs/output/residents_person_entity/*.csv",
    #     header=True,
    #     inferSchema=True
    # )

    residents_entity = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(RPE_PATH)
    
    # residents_alias = spark.read.csv(
    #     "/jobs/output/residents_person_alias/*.csv",
    #     header=True,
    #     inferSchema=True
    # )

    residents_alias = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(RPA_PATH)
    
    # # Read citizens alias from output (generated by citizens deduplication)
    # citizens_alias = spark.read.csv(
    #     "/jobs/output/citizens_person_alias/*.csv",
    #     header=True,
    #     inferSchema=True
    # )

    # Read citizens alias from output (generated by citizens deduplication)
    citizens_alias = spark.read \
        .option("header", str(HAS_HEADER).lower()) \
        .option("inferSchema", str(INFER_SCHEMA).lower()) \
        .option("sep", DELIMITER) \
        .option("mode", "PERMISSIVE") \
        .option("multiLine", "true") \
        .option("quote", '"') \
        .option("escape", '"') \
        .csv(CPA_PATH)
    
    print("✓ All CSV files loaded")
    print(f"  - Residents entities: {residents_entity.count()}")
    print(f"  - Residents aliases: {residents_alias.count()}")
    print(f"  - Citizens aliases: {citizens_alias.count()}")
    
    # Get sponsors from both citizens and residents
    # FIXED: Rename THEN select the renamed column
    all_sponsors = citizens_alias \
        .withColumnRenamed("primary_spm_person_no", "sponsor_spm") \
        .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
        .withColumn("sponsor_type", F.lit("citizen")) \
        .withColumn("sponsor_spm", normalize_digits("sponsor_spm")) \
        .select("sponsor_spm", "sponsor_entity_id", "sponsor_type") \
        .union(
            residents_alias \
            .withColumnRenamed("SPM_PERSON_NO", "sponsor_spm") \
            .withColumnRenamed("entity_person_id", "sponsor_entity_id") \
            .withColumn("sponsor_type", F.lit("resident")) \
            .withColumn("sponsor_spm", normalize_digits("sponsor_spm")) \
            .select("sponsor_spm", "sponsor_entity_id", "sponsor_type")
        )
    
    print(f"✓ Total sponsors available: {all_sponsors.count()}")
    
    # Create sponsorship links
    sponsorship_links = residents_entity.join(
        all_sponsors,
        residents_entity.sponsor_number == all_sponsors.sponsor_spm,
        "left"
    ).filter(
        "sponsor_entity_id IS NOT NULL AND entity_person_id IS NOT NULL"
    ).select(
        F.col("sponsor_entity_id").alias("sponsor_entity_person_id"),
        F.col("entity_person_id").alias("sponsored_entity_person_id"),
        F.col("relation_to_sponsor"),
        F.col("relationship_code"),
        F.col("sponsor_type"),
        F.lit("echannels_residency").alias("source"),
        F.lit(1.0).alias("confidence")
    ).dropDuplicates()
    
    # Create family groups
    family_groups = residents_entity.join(
        all_sponsors,
        residents_entity.sponsor_number == all_sponsors.sponsor_spm,
        "left"
    ).filter("sponsor_entity_id IS NOT NULL").select(
        F.col("entity_person_id"),
        F.col("sponsor_entity_id").alias("sponsor_id"),
        F.col("sponsor_number"),
        F.concat(F.lit("SPON:"), F.col("sponsor_number")).alias("family_group_id"),
        F.lit("sponsorship").alias("source")
    ).dropDuplicates()

        # ---- Write outputs as local CSVs ------------------------------------------
    out_spon = f"{OUTPUT_DIR.rstrip('/')}/residents_sponsorship_links"
    out_fam = f"{OUTPUT_DIR.rstrip('/')}/residents_family_groups"
    
    # Write to CSV files
    print(f"\n✓ Writing {sponsorship_links.count()} sponsorship links")
    sponsorship_links.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .csv(out_spon)
    
    print(f"✓ Writing {family_groups.count()} family groups")
    family_groups.coalesce(1).write \
        .mode("overwrite") \
        .option("header", "true") \
        .csv(out_fam)
    
    print("\n✓ RESIDENTS LINK BUILDER COMPLETE")
    print("Output files saved in:")
    print("  - /jobs/output/residents_sponsorship_links/")
    print("  - /jobs/output/residents_family_groups/")
    
    spark.stop()


if __name__ == "__main__":
    main()
